<?php

namespace Proxies\__CG__\Bufete\AplicacionBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ProcesoJudicial extends \Bufete\AplicacionBundle\Entity\ProcesoJudicial implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Bufete\\AplicacionBundle\\Entity\\ProcesoJudicial' . "\0" . 'id', '' . "\0" . 'Bufete\\AplicacionBundle\\Entity\\ProcesoJudicial' . "\0" . 'descripcion', '' . "\0" . 'Bufete\\AplicacionBundle\\Entity\\ProcesoJudicial' . "\0" . 'titulo', '' . "\0" . 'Bufete\\AplicacionBundle\\Entity\\ProcesoJudicial' . "\0" . 'estado', '' . "\0" . 'Bufete\\AplicacionBundle\\Entity\\ProcesoJudicial' . "\0" . 'codigoConsulta', '' . "\0" . 'Bufete\\AplicacionBundle\\Entity\\ProcesoJudicial' . "\0" . 'fechaIn', '' . "\0" . 'Bufete\\AplicacionBundle\\Entity\\ProcesoJudicial' . "\0" . 'fechaVencimiento', '' . "\0" . 'Bufete\\AplicacionBundle\\Entity\\ProcesoJudicial' . "\0" . 'prioridad', 'abogado', 'cliente', 'documentos');
        }

        return array('__isInitialized__', '' . "\0" . 'Bufete\\AplicacionBundle\\Entity\\ProcesoJudicial' . "\0" . 'id', '' . "\0" . 'Bufete\\AplicacionBundle\\Entity\\ProcesoJudicial' . "\0" . 'descripcion', '' . "\0" . 'Bufete\\AplicacionBundle\\Entity\\ProcesoJudicial' . "\0" . 'titulo', '' . "\0" . 'Bufete\\AplicacionBundle\\Entity\\ProcesoJudicial' . "\0" . 'estado', '' . "\0" . 'Bufete\\AplicacionBundle\\Entity\\ProcesoJudicial' . "\0" . 'codigoConsulta', '' . "\0" . 'Bufete\\AplicacionBundle\\Entity\\ProcesoJudicial' . "\0" . 'fechaIn', '' . "\0" . 'Bufete\\AplicacionBundle\\Entity\\ProcesoJudicial' . "\0" . 'fechaVencimiento', '' . "\0" . 'Bufete\\AplicacionBundle\\Entity\\ProcesoJudicial' . "\0" . 'prioridad', 'abogado', 'cliente', 'documentos');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ProcesoJudicial $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescripcion($descripcion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescripcion', array($descripcion));

        return parent::setDescripcion($descripcion);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescripcion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescripcion', array());

        return parent::getDescripcion();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstado($estado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstado', array($estado));

        return parent::setEstado($estado);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstado', array());

        return parent::getEstado();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodigoConsulta($codigoConsulta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodigoConsulta', array($codigoConsulta));

        return parent::setCodigoConsulta($codigoConsulta);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodigoConsulta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodigoConsulta', array());

        return parent::getCodigoConsulta();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaIn($fechaIn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaIn', array($fechaIn));

        return parent::setFechaIn($fechaIn);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaIn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaIn', array());

        return parent::getFechaIn();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaVencimiento($fechaVencimiento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaVencimiento', array($fechaVencimiento));

        return parent::setFechaVencimiento($fechaVencimiento);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaVencimiento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaVencimiento', array());

        return parent::getFechaVencimiento();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrioridad($prioridad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrioridad', array($prioridad));

        return parent::setPrioridad($prioridad);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrioridad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrioridad', array());

        return parent::getPrioridad();
    }

    /**
     * {@inheritDoc}
     */
    public function setAbogado(\Bufete\AplicacionBundle\Entity\Abogado $abogado = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAbogado', array($abogado));

        return parent::setAbogado($abogado);
    }

    /**
     * {@inheritDoc}
     */
    public function getAbogado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAbogado', array());

        return parent::getAbogado();
    }

    /**
     * {@inheritDoc}
     */
    public function setCliente(\Bufete\AplicacionBundle\Entity\Cliente $cliente = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCliente', array($cliente));

        return parent::setCliente($cliente);
    }

    /**
     * {@inheritDoc}
     */
    public function getCliente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCliente', array());

        return parent::getCliente();
    }

    /**
     * {@inheritDoc}
     */
    public function addDocumento(\Bufete\AplicacionBundle\Entity\Documento $documentos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDocumento', array($documentos));

        return parent::addDocumento($documentos);
    }

    /**
     * {@inheritDoc}
     */
    public function removeDocumento(\Bufete\AplicacionBundle\Entity\Documento $documentos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeDocumento', array($documentos));

        return parent::removeDocumento($documentos);
    }

    /**
     * {@inheritDoc}
     */
    public function getDocumentos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDocumentos', array());

        return parent::getDocumentos();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitulo($titulo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitulo', array($titulo));

        return parent::setTitulo($titulo);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitulo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitulo', array());

        return parent::getTitulo();
    }

}
